name: google_solution_challenge_2024
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  image_picker: ^1.0.7
  provider: ^6.1.1
  easy_localization: ^3.0.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  video_thumbnail: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/Mohamed Raslan.png
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic