name: google_solution_challenge_2024
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  image_picker: ^1.0.7
  provider: ^6.1.1
  firebase_core: ^2.25.2
  firebase_auth: ^4.17.2
  cloud_firestore: ^4.15.2
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
   - assets/images/
   - assets/images/Mohamed Raslan.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic