name: google_solution_challenge_2024
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  image_picker: ^1.0.7
  provider: ^6.1.1
  easy_localization: ^3.0.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  dartz: ^0.10.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  video_thumbnail: ^0.5.3
  video_player: ^2.8.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  readmore: ^2.2.0
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_commons: ^0.6.1
  image: ^4.1.6
  tflite_flutter: '0.10.3'
  path: ^1.8.3
  http: ^1.2.0
  firebase_storage: ^11.6.5
  firebase_database: ^10.4.5
  firebase_crashlytics: ^3.4.14
  firebase_analytics: ^10.8.5
  uuid: ^4.3.3
  flutter_secure_storage: ^9.0.0
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  multi_select_flutter: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 
  build_runner: 
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true


  assets:
   - assets/images/
   - assets/images/Mohamed Raslan.png
   - assets/translations/
   - assets/models/mobileFaceNet.tflite

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic