//================================================================================================================//
//Products
import 'package:google_solution_challenge_2024/features/market_place/domain/product.dart';

List<Product> sampleProducts = [
    Product(
        id: '1',
        name: "Black Jacket",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Clothes/jacketBlack.png",
    ),
    Product(
        id: '2',
        name: "Yellow Jacket",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Clothes/jacketYellow.png",
    ),
    Product(
        id: '3',
        name: "Plain Jersey",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Clothes/jerseyPlain.png",
    ),
    Product(
        id: '4',
        name: "White Shirt",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Clothes/shirtWhite.png",
    ),
    Product(
        id: '5',
        name: "Black Shoe",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Clothes/shoeBlack.png",
    ),
    Product(
        id: '1',
        name: "Blue Shoe",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Clothes/shoeBlue.png",
    ),
    Product(
        id: '2',
        name: "Brown Shoe",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Clothes/shoeBrown.png",
    ),
    Product(
        id: '3',
        name: "Blue Short",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Clothes/shortBlue.png",
    ),
    Product(
        id: '4',
        name: "Brown Short",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Clothes/shortBrown.png",
    ),
    Product(
        id: '5',
        name: "Red Short",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Clothes/shortRed.png",
    ),
    Product(
        id: '1',
        name: "Yellow Short",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Clothes/shortYellow.png",
    ),
    Product(
        id: '2',
        name: "Aqua Shoe",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Clothes/showDarkBlue.png",
    ),
    Product(
        id: '3',
        name: "Beige Shoe",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Clothes/showSkin.png",
    ),
    Product(
        id: '4',
        name: "Yellow Shoe",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Clothes/showYellow.png",
    ),
    ////////////////////////////////////////////////////////////////////////////////////////
    Product(
        id: '1',
        name: "Pot 1",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Handmade/pot1.png",
    ),
    Product(
        id: '2',
        name: "Pot 2",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Handmade/pot2.png",
    ),
    Product(
        id: '3',
        name: "Pot 3",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Handmade/pot3.png",
    ),
    Product(
        id: '4',
        name: "Pot 4",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Handmade/pot4.png",
    ),
    Product(
        id: '5',
        name: "Pot 5",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Handmade/pot5.png",
    ),
    Product(
        id: '1',
        name: "Pot 6",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Handmade/pot6.png",
    ),
    ////////////////////////////////////////////////////////////////////////////////////////
    Product(
        id: '2',
        name: "Home AC",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Home/airConditioner.png",
    ),
    Product(
        id: '3',
        name: "Fridge",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Home/fridge.png",
    ),
    Product(
        id: '4',
        name: "Microwave",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Home/microwave.png",
    ),
    Product(
        id: '5',
        name: "Oven",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Home/oven.png",
    ),
    Product(
        id: '1',
        name: "TV",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Home/tv.png",
    ),
    Product(
        id: '2',
        name: "Washing Machine",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Home/washingMachine.png",
    ),
    ////////////////////////////////////////////////////////////////////////////////////////
    Product(
        id: '3',
        name: "Bolt",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Tools/bolt.png",
    ),
    Product(
        id: '4',
        name: "Compact Screwdriver",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Tools/compactScrewdriver.png",
    ),
    Product(
        id: '5',
        name: "Pliers",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Tools/electricPliers.png",
    ),
    Product(
        id: '1',
        name: "Omni Wrench",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Tools/omniWrench.png",
    ),
    Product(
        id: '2',
        name: "Flat Screwdriver",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Tools/screwdriver.png",
    ),
    Product(
        id: '3',
        name: "Screwdriver",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Tools/screwdriver2.png",
    ),
    Product(
        id: '4',
        name: "T Bolt",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Tools/tScrew.png",
    ),
    Product(
        id: '5',
        name: "Wrench",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Tools/wrench.png",
    ),
    Product(
        id: '1',
        name: "2 Way Wrench",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Tools/wrench2.png",
    )
];

List<Product> sampleToolProducts = [
    Product(
        id: '3',
        name: "Bolt",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Tools/bolt.png",
    ),
    Product(
        id: '4',
        name: "Compact Screwdriver",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Tools/compactScrewdriver.png",
    ),
    Product(
        id: '5',
        name: "Pliers",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Tools/electricPliers.png",
    ),
    Product(
        id: '1',
        name: "Omni Wrench",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Tools/omniWrench.png",
    ),
    Product(
        id: '2',
        name: "Flat Screwdriver",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Tools/screwdriver.png",
    ),
    Product(
        id: '3',
        name: "Screwdriver",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Tools/screwdriver2.png",
    ),
    Product(
        id: '4',
        name: "T Bolt",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Tools/tScrew.png",
    ),
    Product(
        id: '5',
        name: "Wrench",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Tools/wrench.png",
    ),
    Product(
        id: '1',
        name: "2 Way Wrench",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Tools/wrench2.png",
    )
];

List<Product> sampleHomeProducts = [
    Product(
        id: '2',
        name: "Home AC",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Home/airConditioner.png",
    ),
    Product(
        id: '3',
        name: "Fridge",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Home/fridge.png",
    ),
    Product(
        id: '4',
        name: "Microwave",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Home/microwave.png",
    ),
    Product(
        id: '5',
        name: "Oven",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Home/oven.png",
    ),
    Product(
        id: '1',
        name: "TV",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Home/tv.png",
    ),
    Product(
        id: '2',
        name: "Washing Machine",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Home/washingMachine.png",
    ),
];

List<Product> sampleHandmadeProducts = [
    Product(
        id: '1',
        name: "Pot 1",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Handmade/pot1.png",
    ),
    Product(
        id: '2',
        name: "Pot 2",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Handmade/pot2.png",
    ),
    Product(
        id: '3',
        name: "Pot 3",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Handmade/pot3.png",
    ),
    Product(
        id: '4',
        name: "Pot 4",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Handmade/pot4.png",
    ),
    Product(
        id: '5',
        name: "Pot 5",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Handmade/pot5.png",
    ),
    Product(
        id: '1',
        name: "Pot 6",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Handmade/pot6.png",
    ),
];

List<Product> sampleClothesProducts = [
    Product(
        id: '1',
        name: "Black Jacket",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Clothes/jacketBlack.png",
    ),
    Product(
        id: '2',
        name: "Yellow Jacket",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Clothes/jacketYellow.png",
    ),
    Product(
        id: '3',
        name: "Plain Jersey",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Clothes/jerseyPlain.png",
    ),
    Product(
        id: '4',
        name: "White Shirt",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Clothes/shirtWhite.png",
    ),
    Product(
        id: '5',
        name: "Black Shoe",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Clothes/shoeBlack.png",
    ),
    Product(
        id: '1',
        name: "Blue Shoe",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Clothes/shoeBlue.png",
    ),
    Product(
        id: '2',
        name: "Brown Shoe",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Clothes/shoeBrown.png",
    ),
    Product(
        id: '3',
        name: "Blue Short",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Clothes/shortBlue.png",
    ),
    Product(
        id: '4',
        name: "Brown Short",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Clothes/shortBrown.png",
    ),
    Product(
        id: '5',
        name: "Red Short",
        description: "A Very Good Product that is very nice",
        price: 66,
        rating: 4.9,
        stock: 122,
        thumbnail: "assets/images/market_place/Products/Clothes/shortRed.png",
    ),
    Product(
        id: '1',
        name: "Yellow Short",
        description: "A Very Good Product that is very nice",
        price: 23,
        rating: 4.26,
        stock: 132,
        thumbnail: "assets/images/market_place/Products/Clothes/shortYellow.png",
    ),
    Product(
        id: '2',
        name: "Aqua Shoe",
        description: "A Very Good Product that is very nice",
        price: 10,
        rating: 4.52,
        stock: 128,
        thumbnail: "assets/images/market_place/Products/Clothes/showDarkBlue.png",
    ),
    Product(
        id: '3',
        name: "Beige Shoe",
        description: "A Very Good Product that is very nice",
        price: 35,
        rating: 4.89,
        stock: 6,
        thumbnail: "assets/images/market_place/Products/Clothes/showSkin.png",
    ),
    Product(
        id: '4',
        name: "Yellow Shoe",
        description: "A Very Good Product that is very nice",
        price: 46,
        rating: 4.62,
        stock: 136,
        thumbnail: "assets/images/market_place/Products/Clothes/showYellow.png",
    ),
];